language: java
before_install:
- chmod +x gradlew
script:
- "./gradlew build --info"
deploy:
  provider: heroku
  api_key:
    secure: eS62bcUyeW+8LrQQuC515PuDs3ZqIfI3Om5QcGPiOB0IWOPAU0s87/ozfEd6N8pfODD3kZ91jW4+Gmm6How4gv9nZ9RZ2qMHH+Qr6Zq1KIhuDAlN9mOSqpCk9rf880jguz8o1cbmfjJjQ5TmHCdM0dNr7hAyIEo17FMyosaaQkmNG9W1I5wulJQE7EaWIeRuzDvqF9dcTe79qnekKZnsxeLRVnXfFwCjRV7XAO7eIKO9t9tQd12XwO8+S0zDJJ75XMrN+U0U4R0spvdNOB8WcMlr2uOAe3ESyvL/252PT5zJkod3yxO8yqIBUSvT0y7XI1Ki/9oh5nrIaTf1qCg3oJM2eJtNa1wySWtKvkkG9YRRCtakeIiluxsDul7fbuw9HEBVE5MZMCnUBKUg7myVRraLkwtk5doCPlLL1tc9RALM6zudy0e6w9HhCId8k6qvJdlfs+VbpZS3lTM6uDrvTCJb+Yr/VrWpYGJm5l3Q7NK7RoDJTvsNNS7Jug3mdL5/a/t+u6tbOsC0z2J1Bk+t/DgicBngyaK4hQ/UBTB4U6EtEX62ktOEV+mgK0tVC3wE3KtmRZEYFFEMCfq+4hgsRxOdqoRBBy2BNbqdnVSNou90Pmh8qWVr4GlWdb7GWLjkiHwJZOUPjJ75vf9YOAaO5NHLqKdk7VxbjTyvQMeK9r4=
  app: handoverapp
  branches:
    only:
      - main